# Generated by Django 6.0.6 on 2026-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=True, max_length=300, null=True),
        ),
    ]
